### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by fleam** [openset/php2go#53]
..\github.com\openset\php2go\php\directory.go:27:22: cannot use fd (type int) as type syscall.Handle in argument to syscall.Close

**Comment by openset** [comment]
本项目仅供学习使用，不要在生产环境中使用！！！

```go
// Closedir - Close directory's handle
func Closedir(fd int) (err error) {
	return syscall.Close(fd)
}
```
实际使用中不要使用这样的方法，直接调用返回值中的Close方法

**Comment by openset** [comment]
文件相关操作请直接使用ioutil或os包相关方法
```go
ioutil.ReadDir()
os.Open()
```
