### ISSUE TITLE
JsonDecode 对象转数组 返回得是byte

### ISSUE THREAD

**Issue by fleam** [openset/php2go#54]
byte还要转一下变成string

**Comment by openset** [comment]
这个项目的目的不是给用户提供一个和php行为一致的方法库，而是帮助php开发者快速熟悉go语言中相对应的功能。php是弱类型语言，go是强类型语言，使用go时尽量以go的编程规范和思维来写代码。

**Comment by openset** [comment]
在php中处理的可能大多都是字符串，但在go中你将会遇到大量[]byte类型数据流，慢慢去适应，你会更开心。
