### ISSUE TITLE
ArrayColumn这个方法貌似无法满足array_column的返回值吧

### ISSUE THREAD

**Issue by youeryuango** [openset/php2go#56]
> 大神你好，我是新手，不是很懂，这里跟您请教一下ArrayColumn这个问题

`map[string]map[string]interface{}`
##### 而无法像PHP一样做到多维数组中的所有相同key对应的那个val

**Comment by openset** [comment]
@youeryuango 不用怀疑自己。这个项目的目的不是给用户提供一个和php行为一致的方法库，而是帮助php开发者快速熟悉go语言中相对应的功能。php是弱类型语言，go是强类型语言，使用go时尽量以go的编程规范和思维来写代码。
